import { userModel } from '@models/user/user.model';
import { UserDTO, UserEntity } from '@models/user/user.entity';
import {
  PaginatedResponse,
  UUID,
  UserRole,
  UserStatus,
} from '@CustomTypes/common.types';
import { CreateUserInput, UpdateUserInput } from '@validators/user.validator';
import { UserFilters } from './user.filter';
import { emailService } from '@services/notification/email.service';
import { userMapper } from '@mappers/user.mapper';
import { auditService } from '@services/audit/audit.service';
import { ConflictError, NotFoundError } from '@utils/errors';
import crypto from 'crypto';

export class UserService {
  async createUser(input: CreateUserInput, creatorId?: UUID): Promise<UserDTO> {
    const existingUser = await userModel.existsByEmail(input.email);

    if (existingUser) {
      throw new ConflictError('El email ya está registrado');
    }

    let password = input.password;
    let autoGenerated = false;

    if (!password) {
      password = crypto.randomBytes(8).toString('hex');
      autoGenerated = true;
    }

    const newUser = await userModel.create(input, password);

    await emailService.sendWelcomeEmail(
      newUser.email,
      newUser.firstName,
      password
    );

    if (creatorId) {
      await auditService.log(
        'CREATE_USER',
        'user',
        newUser.id,
        {
          email: newUser.email,
          role: newUser.role,
          autoGeneratedPassword: autoGenerated,
        },
        creatorId
      );
    }

    return userMapper.toDTO(newUser);
  }

  async getUserById(id: string): Promise<UserDTO> {
    const user = await userModel.getById(id as UUID);

    if (!user) throw new NotFoundError('Usuario no encontrado');

    return userMapper.toDTO(user);
  }

  async getUserByEmail(email: string): Promise<UserEntity> {
    return await userModel.getByEmail(email);
  }

  async listUsers(
    page: number,
    limit: number,
    filters: UserFilters,
    groupId?: string
  ): Promise<PaginatedResponse<UserEntity>> {
    filters.groupId = groupId;
    return await userModel.list(page, limit, filters);
  }

  async getProfile(userId: string): Promise<UserDTO> {
    const user = await userModel.getById(userId as UUID);

    if (!user) {
      throw new NotFoundError('Usuario no encontrado');
    }

    const userDTO = userMapper.toDTO(user);

    const enrollments = await userModel.getEnrollments(userId);

    userDTO.enrollments = enrollments.map((e) => ({
      subjectName: e.subject_name,
      groupName: e.group_name,
      academicYear: e.academic_year,
      role: e.role,
    }));

    return userDTO;
  }

  async findOrCreateStudent(
    email: string,
    firstName: string,
    lastName: string
  ): Promise<UserDTO> {
    const existingUser = await userModel.findByEmail(email);

    if (existingUser) {
      return userMapper.toDTO(existingUser);
    }

    const password = crypto.randomBytes(8).toString('hex');

    const newUser = await userModel.create(
      {
        email,
        firstName,
        lastName,
        role: UserRole.STUDENT,
        status: UserStatus.ACTIVE,
        preferredLanguage: 'es',
      },
      password
    );

    await emailService.sendWelcomeEmail(
      newUser.email,
      newUser.firstName,
      password
    );

    return userMapper.toDTO(newUser);
  }

  async updateProfile(
    userId: string,
    input: UpdateUserInput
  ): Promise<UserDTO> {
    const user = await userModel.getById(userId as UUID);

    if (!user) {
      throw new NotFoundError('Usuario no encontrado');
    }

    await userModel.update(userId as UUID, {
      firstName: input.firstName,
      lastName: input.lastName,
      phone: input.phone,
      bio: input.bio,
      preferredLanguage: input.preferredLanguage,
    });

    await auditService.log(
      'UPDATE_PROFILE',
      'user',
      userId,
      input,
      userId as UUID
    );

    const updatedUser = await userModel.getById(userId as UUID);
    const userDTO = userMapper.toDTO(updatedUser!);

    const enrollments = await userModel.getEnrollments(userId as UUID);
    userDTO.enrollments = enrollments.map((e) => ({
      subjectName: e.subject_name,
      groupName: e.group_name,
      academicYear: e.academic_year,
      role: e.role,
    }));

    return userDTO;
  }

  async changeRole(id: string, role: UserRole): Promise<UserEntity> {
    return await userModel.updateRole(id as UUID, role);
  }

  async changeStatus(id: string, status: UserStatus): Promise<UserEntity> {
    return await userModel.updateStatus(id as UUID, status);
  }

  async deleteUser(id: string, deleterId?: UUID): Promise<void> {
    const user = await userModel.getById(id as UUID);

    if (!user) throw new NotFoundError('Usuario no encontrado');

    await userModel.softDelete(id as UUID);

    if (deleterId) {
      await auditService.log(
        'DELETE_USER',
        'user',
        id as UUID,
        { email: user.email },
        deleterId
      );
    }
  }

  // --- SPECIFIC LISTS ---

  async getTeachers(): Promise<UserEntity[]> {
    return await userModel.getTeachers();
  }

  async getStudents(): Promise<UserEntity[]> {
    return await userModel.getStudents();
  }
}

export const userService = new UserService();
